# Generated by Django 5.1 on 2025-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
