# Generated by Django 5.1 on 2025-02-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_remove_capsuletoy_category_capsuletoy_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuletoy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsuletoy',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
